spring:
  application:
  name: banking-service-registry

  output:
    ansi:
      enabled: always

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
